<?php

declare(strict_types=1);

namespace Php\Support\Laravel\Database\Tests\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @property string $id
 * @property string $name
 * @property string $enabled
 * @mixin Builder
 */
class TestModel extends Model
{
    protected $keyType = 'string';

    // The key is a UUID generated by the database, not a sequence.
    public $incrementing = false;

    protected $table = 'tests';
}
